---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: demo-operators
  namespace: edge-clusters
spec:
  paths:
    - olm-operators
  repo: "https://github.com/edge-orchestration/app-fleet-demo"
  branch: "0.3.0"
  targets:
    - name: manufacturing-edge-clusters
      clusterSelector:
        matchLabels:
          industry: manufacturing
