---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: postgres-operator
  namespace: edge-clusters
spec:
  paths:
    - olm-operators/postgres
  repo: "https://github.com/edge-orchestration/app-fleet-demo"
  branch: "0.3.2"
  targets:
    - name: manufacturing-edge-clusters
      clusterSelector:
        matchLabels:
          industry: manufacturing
